jobstargram/cranejob

- build.gradle
> feat: 의존성 추가(JPA, MySQL)

- src/main/java/com/est/cranejob/user/domain/DeletedUser.java
- src/main/java/com/est/cranejob/user/domain/PenaltyReason.java
- src/main/java/com/est/cranejob/user/domain/Role.java
- src/main/java/com/est/cranejob/user/domain/RoleName.java
- src/main/java/com/est/cranejob/user/domain/User.java
- src/main/java/com/est/cranejob/user/domain/UserPenalty.java
- src/main/java/com/est/cranejob/user/domain/UserStatus.java
- User 디렉토리의 엔티티 및 연관 관계 매핑 작성 했습니다.
- createdAt, updatedAt, deletedAt과 관련된 메서드는 어떤 식으로 작성해야 할 지 아직 잘 모르겠어서 좀 더 찾아보고 수정 하겠습니다.
> feat: 유저 엔티티 작성

- build.gradle
- src/main/java/com/est/cranejob/user/domain/DeletedUser.java
- src/main/java/com/est/cranejob/user/domain/Role.java
- src/main/java/com/est/cranejob/user/domain/User.java
- src/main/resources/application.yml
jpa, mysql 설정이 안되어 있어서 build.gradle 파일에서 일부로 제외해야하는게 불편한것 같아서 이번기회에 좀 맞춰보면 좋을 듯 합니다.
해당 설정값은 별도의 외부 파일로 분리하고 그 파일은 git추적을 못하게 만들겠습니다
> 오타 수정 및 의존성 재주입

- src/main/java/com/est/cranejob/comment/domain/Comment.java
- src/main/java/com/est/cranejob/post/domain/Announcement.java
- src/main/java/com/est/cranejob/post/domain/Post.java
- src/main/java/com/est/cranejob/user/dto/request/CreateUserRequest.java
- src/main/java/com/est/cranejob/user/dto/request/LoginRequest.java
- src/main/java/com/est/cranejob/user/dto/request/UpdateUserRequest.java
- 게시글, 댓글 엔티티 및 연관관계 작성 햇습니다.
- 컬럼 네이밍에 오타가 있어서 수정했습니다.
- 로그인, 회원가입, 회원 정보 수정(비밀번호, 이름) DTO 작성 했습니다.
> feat: 엔티티 및 DTO 작성

- build.gradle
- src/main/java/com/est/cranejob/recruit/controller/RecruitController.java
- src/main/java/com/est/cranejob/recruit/dto/CreateRecruit.java
- src/main/java/com/est/cranejob/recruit/dto/RecruitInfo.java
- src/main/java/com/est/cranejob/recruit/service/HttpURLConnectionEx.java
- src/main/java/com/est/cranejob/recruit/service/RecruitService.java
수행한 코드
- DTO작성
- Controller 작성
- Service 작성
- 의존성(GSON) 주입 
계획
- html 수정
- thymeleaf 작성
> 사람인 API 받아오기

- src/main/java/com/est/cranejob/announcement/dto/request/CreateAnnouncementRequest.java
- src/main/java/com/est/cranejob/announcement/dto/request/UpdateAnnouncementRequest.java
- src/main/java/com/est/cranejob/announcement/dto/response/AnnouncementDetailResponse.java
- src/main/java/com/est/cranejob/announcement/dto/response/AnnouncementResponse.java
- src/main/java/com/est/cranejob/comment/dto/request/CreateCommentRequest.java
- src/main/java/com/est/cranejob/comment/dto/request/UpdateCommentRequest.java
- src/main/java/com/est/cranejob/comment/dto/response/CommentDetailResponse.java
- src/main/java/com/est/cranejob/comment/dto/response/CommentResponse.java
- src/main/java/com/est/cranejob/post/dto/request/CreatePostRequest.java
- src/main/java/com/est/cranejob/post/dto/request/UpdatePostRequest.java
- src/main/java/com/est/cranejob/post/dto/response/PostAdminDetailResponse.java
- src/main/java/com/est/cranejob/post/dto/response/PostSummaryResponse.java
- src/main/java/com/est/cranejob/post/dto/response/PostUserDetailResponse.java
- 게시글, 댓글, 공지사항 생성 및 수정 Request DTO 작성했습니다.
- 댓글 보기(유저), 상세보기(관리자) Response DTO 작성했습니다.
- 게시글 요약 보기(유저), 상세보기(유저), 상세보기(관리자) Response DTO 작성했습니다.
> feat: DTO 작성

- src/main/java/com/est/cranejob/recruit/controller/RecruitController.java
- src/main/resources/application.yml
- src/main/resources/static/assets/dist/css/style.css
- src/main/resources/templates/recruit/recruit-list.html
- 디자인은 유지한채 API를 띄워봤습니다.
- 수정이 더 필요합니다. 주말에 하겠습니다.
> 타임리프 & html 수정

- src/main/java/com/est/cranejob/user/controller/AdminUserController.java
- src/main/java/com/est/cranejob/user/controller/UserController.java
- src/main/java/com/est/cranejob/user/dto/request/CreateAdminUserRequest.java
- src/main/java/com/est/cranejob/user/dto/request/UpdateAdminUserRequest.java
- src/main/java/com/est/cranejob/user/dto/request/UpdateUserRequest.java
- src/main/java/com/est/cranejob/user/service/AdminUserService.java
- src/main/resources/templates/admin/edit.html
- src/main/resources/templates/admin/signup.html
- src/main/resources/templates/post/list.html
일반 사용자, 관리자 사용자 정보 수정 시 validation 체크 오류 수정
- UpdateUserReseponse, UpdateAdminUserResponse 클래스에 UserResponse를 받아서 반환해주는 빌더 메소드 추가
> 일반 사용자, 관리자 사용자 정보 수정 시 validation 체크 오류 수정

- src/main/java/com/est/cranejob/post/controller/UserPostController.java
- src/main/java/com/est/cranejob/post/service/PostService.java
- src/main/resources/templates/post/form.html
- src/main/resources/templates/post/list.html
- 게시글 작성 컨트롤러 및 서비스 로직 작성 했습니다
- 오류 사항
-  게시글 제목과 내용을 작성 후 저장 버튼을 누르면 login 페이지로 넘어감(예시)
- 오류 로그(로그인 되지 않은 사용자라고 뜸)
- 인증된 사용자를 불러오는 로직에서 이상이 있는것 같은데 어떻게 해결해야 할지 잘 모르겠습니다.
> err: 게시글 컨트롤러, 서비스, 개시글 추가폼 작성(수정 필요)

- src/main/java/com/est/cranejob/post/controller/UserPostController.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/java/com/est/cranejob/security/provider/FormAuthenticationProvider.java
- src/main/java/com/est/cranejob/user/controller/AdminUserController.java
- src/main/resources/templates/admin/login.html
- 기존에 일반 사용자가 관리자 로그인 페이지에서 로그인 되는 오류 수정
- 관리자가 일반 사용자 로그인 페이지에서 로그인 되는 오류 수정
> fix: 권한별 로그인 페이지 기능 오류 수정

- src/main/java/com/est/cranejob/HomeController.java
- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/announcement/repository/AnnouncementRepository.java
- src/main/java/com/est/cranejob/announcement/service/AnnouncementService.java
- src/main/java/com/est/cranejob/post/controller/UserPostController.java
- src/main/java/com/est/cranejob/post/dto/response/PostSummaryResponse.java
- src/main/java/com/est/cranejob/post/repository/PostRepository.java
- src/main/java/com/est/cranejob/post/service/PostService.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/resources/templates/post/list.html
게시글 작성시 로그인 화면으로 리다이렉트되는 부분 수정했습니다.
아직 security가 익숙하지 않아서 권한 이슈가 계속 생기는데 지속적으로 말씀해주시면 최대한 빠르게 해결하겠습니다.
감사합니다.
> fix: 게시글 작성시 로그인 화면으로 리다이렉트되는 오류 수정

- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/announcement/dto/AdminUpdateUserRequest.java
- src/main/java/com/est/cranejob/announcement/service/AnnouncementService.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/java/com/est/cranejob/user/domain/User.java
- src/main/java/com/est/cranejob/user/dto/response/UserResponse.java
- src/main/java/com/est/cranejob/user/repository/UserRepository.java
- src/main/resources/templates/admin/user-info.html
- src/main/resources/templates/admin/user-list.html
- src/main/resources/templates/post/list.html
[관리자] 유저 내역 리스트 페이지에서 유저 역할, 상태 변경 기능 구현
> feat: [관리자] 유저 내역 리스트 페이지에서 유저 역할, 상태 변경 기능 구현

- src/main/java/com/est/cranejob/recruit/controller/RecruitController.java
- src/main/java/com/est/cranejob/recruit/repository/RecruitRepository.java
- src/main/java/com/est/cranejob/recruit/service/RecruitService.java
- src/main/resources/templates/recruit/recruit-list.html
- 페이징 기능 완료
- 검색 기능 완료
- 추후 작업 : html 정리 & url 연동
> 페이징, 검색 기능 완료

- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/user/controller/UserController.java
- src/main/java/com/est/cranejob/user/domain/User.java
- src/main/java/com/est/cranejob/user/dto/request/UpdateUserRequest.java
- src/main/java/com/est/cranejob/user/service/UserService.java
- src/main/resources/templates/user/edit.html
> feat: 유저 탈퇴 기능 구현

- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/announcement/domain/Announcement.java
- src/main/java/com/est/cranejob/announcement/dto/request/CreateAnnouncementRequest.java
- src/main/java/com/est/cranejob/announcement/dto/request/UpdateAnnouncementRequest.java
- src/main/java/com/est/cranejob/announcement/service/AnnouncementService.java
- src/main/java/com/est/cranejob/recruit/service/SchedulerService.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/resources/templates/announcement/edit.html
- src/main/resources/templates/announcement/form.html
- src/main/resources/templates/layout/header.html
- src/main/resources/templates/post/list.html
- src/main/resources/templates/user/edit.html
> feat: 공지사항 수정 기능 추가 

- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/announcement/domain/Announcement.java
- src/main/java/com/est/cranejob/announcement/dto/response/AnnouncementResponse.java
- src/main/java/com/est/cranejob/announcement/repository/AnnouncementRepository.java
- src/main/java/com/est/cranejob/announcement/service/AnnouncementService.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/resources/templates/announcement/edit.html
- src/main/resources/templates/announcement/form.html
- src/main/resources/templates/announcement/list.html
- src/main/resources/templates/layout/header.html
관리자 로그인 후
공지사항과 관련된 CRUD 구현했습니다.
기능구현하는 과정에서 url를 조금 restful 처럼 작성해봤습니다.
> feat: 공지사항 CRUD 기능구현

- src/main/java/com/est/cranejob/announcement/controller/AnnouncementController.java
- src/main/java/com/est/cranejob/announcement/dto/request/UpdateAnnouncementRequest.java
- src/main/java/com/est/cranejob/announcement/service/AnnouncementService.java
- src/main/java/com/est/cranejob/recruit/service/SchedulerService.java
- src/main/java/com/est/cranejob/security/config/SecurityConfig.java
- src/main/resources/templates/recruit/recruit-list.html
채용공고 디자인 변경과 ScheduleService 오타 수정했습니다!
> feat: 채용공고 디자인 변경

- src/main/java/com/est/cranejob/comment/controller/CommentController.java
- src/main/java/com/est/cranejob/comment/repository/CommentRepository.java
- src/main/java/com/est/cranejob/comment/service/CommentService.java
- src/main/java/com/est/cranejob/post/controller/UserPostController.java
- src/main/resources/templates/post/userDetail.html
- 작성된 댓글은 확인가능 - DB에 직접 넣어서 확인
- 댓글 작성은 401 인증 에러
- 로그
- 콘솔 로그
> err: 게시글 상세페이지 댓글 작성 및 확인

- src/main/resources/templates/admin/edit.html
- src/main/resources/templates/admin/login.html
- src/main/resources/templates/admin/signup.html
- src/main/resources/templates/admin/user-info.html
- src/main/resources/templates/admin/user-list.html
- src/main/resources/templates/post/edit.html
- src/main/resources/templates/post/form.html
- src/main/resources/templates/post/list.html
- src/main/resources/templates/post/userDetail.html
- src/main/resources/templates/user/edit.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/signup.html
상단바 div th:replace="~{/layout/header.html :: header}" /div 로 교체
게시글 리스트에 여백 생성
버튼 색 수정
post > form.html
post > edit.html
위의 두 가지 html파일에 css 추가
위 사항들 완료하였습니다.
> 게시글 부분 css 작업

- src/main/resources/templates/recruit/recruit-list.html
> 채용 페이지 css 마무리

- src/main/resources/application.yml
- port 번호 변수화 
- RDS 데이터베이스 info 변수화
> 무중단 배포를 위한 yml 코드 수정

- src/main/resources/templates/announcement/list.html
> style: css 수정

- src/main/java/com/est/cranejob/recruit/service/SchedulerService.java
- src/main/resources/templates/admin/edit.html
- src/main/resources/templates/admin/login.html
- src/main/resources/templates/admin/signup.html
- src/main/resources/templates/admin/user-info.html
- src/main/resources/templates/admin/user-list.html
- src/main/resources/templates/announcement/detail.html
- src/main/resources/templates/announcement/edit.html
- src/main/resources/templates/announcement/form.html
- src/main/resources/templates/announcement/list.html
- src/main/resources/templates/post/edit.html
- src/main/resources/templates/post/form.html
- src/main/resources/templates/post/list.html
- src/main/resources/templates/post/postDetail.html
- src/main/resources/templates/recruit/recruit-list.html
- src/main/resources/templates/user/edit.html
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/signup.html
- 배포 중 발생한 경로 문제 해결
- 채용페이지 더미 데이터 삽입을 위한 스케쥴러 수정
> 배포 에러에 대한 코드 수정

- src/main/resources/templates/layout/header.html
- src/main/resources/templates/post/postDetail.html
댓글 작성 버튼 위치 조정과 헤더에 CraneJob 문구 입력 완료하였습니다.
> header and delete button
